# Generated by Django 4.2 on 2023-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_per_week', models.IntegerField()),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
