# Generated by Django 4.2 on 2023-07-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages_Plan', '0002_alter_subscription_cost_per_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cost_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
