# Generated by Django 4.2.3 on 2023-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_category_description_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='heating_instruction',
            field=models.TextField(default='Instructions not available'),
        ),
        migrations.AddField(
            model_name='food',
            name='nutrition_facts_ingredients',
            field=models.TextField(default=' Facts not available'),
        ),
    ]
