# Generated by Django 4.2.3 on 2023-07-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_food_heating_instruction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
