# Generated by Django 4.2 on 2023-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_food_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.ImageField(
                blank=True, null=True, upload_to='food_images'),
        ),
    ]
