# Generated by Django 4.2 on 2023-07-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_food_nutrition_facts_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost_per_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
