# Generated by Django 4.2 on 2023-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_food_cost_per_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='filters',
            field=models.ManyToManyField(to='menu.filteroption'),
        ),
    ]
